export const estadoUFMap: Record<string, string> = {
  "Acre": "AC",
  "Alagoas": "AL",
  "Amapá": "AP",
  "Amazonas": "AM",
  "Bahia": "BA",
  "Ceará": "CE",
  "Distrito Federal": "DF",
  "Espírito Santo": "ES",
  "Goiás": "GO",
  "Maranhão": "MA",
  "Mato Grosso": "MT",
  "Mato Grosso do Sul": "MS",
  "Minas Gerais": "MG",
  "Pará": "PA",
  "Paraíba": "PB",
  "Paraná": "PR",
  "Pernambuco": "PE",
  "Piauí": "PI",
  "Rio de Janeiro": "RJ",
  "Rio Grande do Norte": "RN",
  "Rio Grande do Sul": "RS",
  "Rondônia": "RO",
  "Roraima": "RR",
  "Santa Catarina": "SC",
  "São Paulo": "SP",
  "Sergipe": "SE",
  "Tocantins": "TO",
};

export const estadosBrasileiros = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "Santa Catarina",
  "São Paulo",
  "Sergipe",
  "Tocantins",
];

export const servicosAdicionais = [
  {
    id: "apostilamento",
    name: "Apostilamento Digital",
    description: "Registro digital adicional para documentos oficiais.",
    price: 300,
    color: "bg-blue-100",
  },
  {
    id: "traducao",
    name: "Tradução Juramentada",
    description: "Cópia traduzida com valor legal em português.",
    price: 449.9,
    color: "bg-amber-100",
  },
  {
    id: "inteiro_teor",
    name: "Inteiro Teor Digitada",
    description: "Versão completa e fiel do registro.",
    price: 99.9,
    color: "bg-slate-100",
  },
  {
    id: "copia_reprografica",
    name: "Cópia Reprográfica",
    description: "Cópia fiel do documento original.",
    price: 99.9,
    color: "bg-violet-100",
  },
  {
    id: "aviso_recebimento",
    name: "Aviso de Recebimento (AR)",
    description: "Confirmação de entrega pelos Correios.",
    price: 24.9,
    color: "bg-emerald-100",
  },
  {
    id: "previa_digital",
    name: "Prévia Digital",
    description: "Visualize o pedido antes de finalizar.",
    price: 24.9,
    color: "bg-cyan-100",
  },
];
